services:
  backend:
    build:
      context: ./backend

    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=test
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=base_test
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - JWT_SECRET=dev-secret-key
      - JWT_REFRESH_SECRET=dev-refresh-secret
      - BLOCKCHAIN_PRIVATE_KEY=0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
      - BLOCKCHAIN_RPC_URL=https://sepolia.base.org
      - USDC_CONTRACT_ADDRESS=0x036CbD53842c5426634e7929541eC2318f3dCF7e
    
    depends_on:
      - postgres
      - redis
    
    volumes:
      - ./backend:/app
      - ./backend:/app/logs
    restart: unless-stopped
  
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=base_test
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./backend/src/database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped


  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

